CREATE TABLE IF NOT EXISTS videos (
	NAME VARCHAR(255),
	CATEGORY_ID VARCHAR(255),
	TIMESTAMP_SECONDS INT
);

CREATE TABLE IF NOT EXISTS categories (
	CATEGORY_ID VARCHAR(255),
	CATEGORY_NAME VARCHAR(255)
);